config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  resources :users, except: [:index, :new, :create]

  resources :screens do
    resources :movies
  end

  # get '/home', to: 'pages#home'

  root 'pages#home'
  # root 'screens#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :screen

  validates :title, :context, :showtime, presence: true
end
  

app/models/screen.rb
class Screen < ApplicationRecord
  has_many :movies, dependent: :destroy

  validates :room_no, :capacity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[a-z\d]{1}+[\w.+%-]+@[a-z\d]{1}+(?:[a-z\d\-]+\.)+[a-z]{2,}\z/i

  has_secure_password

  before_save { self.username = username.downcase }
  before_save { self.email = email.downcase }


  validates :username, :email, :password,
    presence: true

  validates :username, :password,
    length: { minimum: 6 }

  validates :username, :email,
    uniqueness: { case_sensitive: false }

  validates :email,
    format: { with: VALID_EMAIL_REGEX }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_screen_movie
  before_action :set_movie, except: [:index, :new, :create]

  def index
    @movies = Movie.all # necessary?
  end

  def show
  end

  def new
    @movie = @screen.movies.new
  end

  def create
    @movie = @screen.movies.new(movie_params)

    if @movie.save
      redirect_to screen_movie_url(@screen, @movie)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to screen_movie_url(@screen, @movie)
    else
      render 'edit'
    end
  end

  def destroy
    @movie.destroy
    redirect_to @screen
  end

  private

  def set_screen_movie
    @screen = Screen.find(params[:screen_id])
  end

  def set_movie
    @movie = @screen.movies.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :context, :showtime)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_action :set_screen, except: [:index, :new, :create]

  def index
    @screens = Screen.all
  end

  def show
  end

  def new
    @screen = Screen.new
  end

  def create
    @screen = Screen.new(screen_params)
    if @screen.save
      redirect_to @screen
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @screen.update(screen_params)
      redirect_to @screen
    else
      render 'edit'
    end
  end

  def destroy
    @screen.destroy
    redirect_to screens_url
  end

  private

  def set_screen
    @screen = Screen.find(params[:id])
  end

  def screen_params
    params.require(:screen).permit(:room_no, :capacity)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      login(user)
      redirect_to screens_url
    else
      flash.now[:danger] = 'Invalid username/password.'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User deleted."
    redirect_to root_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def head_title(page_title="")
    base_title = "CineMix"
    if !page_title.empty?
      "#{base_title} - #{page_title}"
    else
      base_title
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    # find raises exception if user_id doesn't exist
    # so use find_by instead
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    current_user == user
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>Copyright &copy; Thùy Ngô</footer>

app/views/layouts/_header.html.erb
<header><h1><%= link_to head_title, root_path %></h1></header>

app/views/layouts/_navbar.html.erb
<nav class="nav">

  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <% if logged_in? %>
      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Log in', login_path %></li>
    <% end %>
  </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= head_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flex-container">
      <%= render 'layouts/header'%>
      <%= render 'layouts/navbar'%>
      <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{msg_type}" ) %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>

    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/movies/_errors.html.erb
<div>

<% if @movie.errors.any? %>
  <div>
    <h3>
      <%= pluralize(@movie.errors.count, "error") %> prohibited
      this article from being saved:
    </h3>

    <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</div>

app/views/movies/_form.html.erb
<div>
  <%= form_for([@screen, @screen.movies.build]) do |f| %>
    <%= render 'errors' %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :context %>
      <%= f.text_area :context %>
    </p>
    <p>
      <%= f.label :showtime %>
      <%= f.time_field :showtime %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/movies/edit.html.erb
<% provide(:title, 'Edit movie') %>
<% provide(:submit_btn, 'Save changes') %>

<article class="article">
  <h1><%= yield(:title)%></h1>
  <div>
    <%= render 'form' %>
  </div>
</article>

app/views/movies/index.html.erb
<% provide(:title, 'Movies') %>

<div class='article'>
  <h1><%= yield(:title) %></h1>

  <table>
    <tr>
      <th>Screen No.</th>
      <th>Title</th>
      <th>Time</th>
    </tr>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.screen.room_no %></td>
        <td><%= link_to movie.title, screen_movie_path(movie.screen, movie) %></td>
        <td><%= movie.showtime %></td>
      </tr>
    <% end  %>
  </table>
</div>

app/views/movies/new.html.erb
<% provide(:title, 'Add movie') %>
<% provide(:submit_btn, 'Save movie') %>

<article class="article">
  <h1><%= yield(:title)%></h1>
  <div>
    <%= render 'form' %>
  </div>
</article>

app/views/movies/show.html.erb
<% provide(:title, @movie.title) %>

<article class="article">
  <h1><%= @movie.title %></h1>
  <p><%= @movie.context %></p>
  <p><strong><%= @movie.showtime %></strong></p>

  <p><%= link_to "Update movie", edit_screen_movie_path(@screen,@movie)%></p>
  <p><%= link_to "Delete movie", screen_movie_path(@screen, @movie),
    method: :delete,
    data: { confirm: 'Are you sure?' } %></p>
  <p><%= link_to "Back to Screen #{@screen.room_no}", screen_path(@screen)%></p>
</article>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<article class="article">
  <h1>La Jetée</h1>
  <p>A narrative told almost completely through photomontage. Taking place in a post-apocolyptic Paris, it's a story about time-travel, memories that persist and the inescapability of fate. If you have seen <i>12 Monkeys</i>, some of the concepts and the storyline were inspired by <i>La Jetée</i>.</p>
  <p><strong>11:15 am</strong></p>
</article>

app/views/screens/_errors.html.erb
<div>

<% if @screen.errors.any? %>
  <div>
    <h2>
      <%= pluralize(@screen.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>

    <ul>
      <% @screen.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</div>

app/views/screens/_form.html.erb
<div>
  <%= form_for @screen do |f| %>
    <%= render 'errors' %>
    <p>
      <%= f.label :room_no %>
      <%= f.number_field :room_no %>
    </p>
    <p>
      <%= f.label :capacity %>
      <%= f.number_field :capacity %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/screens/edit.html.erb
<% provide(:title, 'Edit screen') %>
<% provide(:submit_btn, 'Save changes') %>

<article class="article">
  <h1><%= yield(:title) %></h1>
  <div>
    <%= render 'form' %>
  </div>
</article>

app/views/screens/index.html.erb
<% provide(:title, "Screens") %>

<div class="article">
  <h1><%= yield(:title)%></h1>
  <table>
    <tr>
      <th>Screen No.</th>
      <th>Capacity</th>
    </tr>
    <% @screens.each do |screen| %>
      <tr>
        <td><%= link_to screen.room_no, screen_path(screen) %></td>
        <td><%= screen.capacity %></td>
      </tr>
    <% end %>
  </table>
  <p><%= link_to "Add a screen", new_screen_path %></p>
</div>

app/views/screens/new.html.erb
<% provide(:title, 'Create screen') %>
<% provide(:submit_btn, 'Save screen') %>

<article class="article">
  <h1><%= yield(:title) %></h1>
  <div>
    <%= render 'form' %>
  </div>
</article>

app/views/screens/show.html.erb
<% provide(:title, @screen.room_no.to_s) %>

<div class="article">
  <h2>Room no: <%= @screen.room_no %></h2>
  <h2>Capacity: <%= @screen.capacity %></h2>

  <div>
    <ul>
      <% @screen.movies.each do |movie| %>
        <li><%= link_to movie.title, screen_movie_path(@screen, movie) %></li>
      <% end %>
    </ul>
  </div>

  <p><%= link_to "Update Screen", edit_screen_path(@screen) %></p>
  <p><%= link_to "Delete Screen", screen_path(@screen),
    method: :delete,
    data: { confirm: 'You are also deleting all the movies. Are you sure?' } %></p>
  <p><%= link_to 'Add a movie', new_screen_movie_path(@screen)%></p>
</div>

app/views/users/_errors.html.erb
<div>

<% if @user.errors.any? %>
  <div id="error_message">
    <h3>
      <%= pluralize(@user.errors.count, "error") %> prohibited
      this article from being saved:
    </h3>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

</div>

app/views/users/_form.html.erb
<div>
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'errors' %>
    <p>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>
<% provide(:submit_btn, 'Save profile') %>

<article class="article">
  <h1><%= yield(:title) %></h1>
  <div>
    <%= render 'form' %>
  </div>
</article>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<% provide(:submit_btn, 'Save registration') %>

<article class="article">
  <h1><%= yield(:title) %></h1>
  <div>
    <%= render 'form' %>
  </div>
</article>

app/views/users/show.html.erb
<% provide(:title, @user.username)%>

<div class="article">
  <h1><%= @user.username %></h1>
</div>